### ISSUE TITLE
Challenges faced

### ISSUE THREAD

**Issue by Wamundila** [bongohive-internship/css-introduction-assignment-Wamundila#7]
**Is this about this assignment?**
Yes

****
I took note of the advice provided in this [issue](https://github.com/BongoHive/internship-program/issues/9) about doing as many tasks as possible.
I'm moving on to the javaScript section now. Hope you'll  also consider that i had faced [challenges](https://github.com/BongoHive/internship-program/issues/17) in setting up the assignment repositories, which was resolved on wednesday afternoon.

**Comment by Joebbrien** [comment]
Hi @Wamundila 

we took not of this issue and that is why we had to extend the deadline

Thanks
